### ISSUE TITLE
Some JPG break jpeg-recompress with -smallfry

### ISSUE THREAD

**Issue by xberg** [danielgtaylor/jpeg-archive#58] opened 2017-03-22 15:41 UTC
Hi,
I have a few JPG that break jpeg recompress with I use the method smallfry. I am running the windows executable V2.1.1. No error message: just a windows popup that jpeg-recompress has stopped running. 
It breaks just after displaying "Metadata size is xx kb".

If I use ssim as a method on the same files it's OK.
This happened on about 15 to 20% of tested files.

**Comment by prdolmos** [comment] 2017-04-05 12:55
It has to do with the images' dimensions:

https://github.com/danielgtaylor/jpeg-archive/issues/24

**Comment by lfos** [comment] 2017-12-09 08:53
Closing this as it seems to be a dupe of issue #24.

**Closed by lfos** 2017-12-09 08:53 UTC
