### ISSUE TITLE
jpeg-recompress Feature request: Simple timestamp manipulation: arg to optionally preserve timestamps

### ISSUE THREAD

**Issue by Zcehtro** [danielgtaylor/jpeg-archive#97] opened 2018-08-20 22:33 UTC
I'd like to process this on ALL my JPG's.
However, doing so would override all the timestamps for Date Modified.
Could you implement a feature to preserve the file's timestamps?
I suppose it would word like: get file, get current timestamps, store timestamps, process file, apply stored timestamps, next file...
A simple argument would do it.

Am using this a lot. Great work and thank you!

Currently running Windows 10.

**Comment by lfos** [comment] 2018-08-21 03:56
Duplicate of #46.

**Closed by lfos** 2018-08-21 03:56 UTC
